name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "7.0.x"

      - name: Build
        run: dotnet build --configuration Release

  test:
    needs: build
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306:3306
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Start MySQL service
        run: sudo systemctl start mysql

  
      - name: Check MySQL service status
        run: systemctl status mysql
  
      - name: Set up database
        run: mysql -u root -p<password> -h localhost -P 3306 < robot4careDatabase.sql

      - name: Build
        run: dotnet build --configuration Release

      - name: Test
        run: dotnet test --no-restore --verbosity normal
