name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "7.0.x"

      - name: Build
        run: dotnet build --configuration Release

  test:
    needs: build
    runs-on: ubuntu-latest
    env:
      DB_CONNECTION: mysql
      DB_HOST: localhost
      DB_PORT: 3306
      DB_DATABASE: robot4care
      DB_USERNAME: root
      DB_PASSWORD: root
    services:
      mysql:
          image: mysql:latest
          env:
              MYSQL_DATABASE: robot4care
              MYSQL_USER: robot
              MYSQL_PASSWORD: robot
              MYSQL_ROOT_PASSWORD: robot
          ports:
              - 3306
          options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=5
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
  
      - name: Set up database
        run: |
          sudo systemctl start mysql
          sudo mysql -uroot -proot -h 127.0.0.1 -e 'CREATE DATABASE robot4care;'
          sudo mysql -uroot -proot -h 127.0.0.1 robot4care < ./robot4careDatabase.sql
        
      - name: Check MySQL service journal
        run: journalctl -xeu mysql.service
      
      - name: Start MySQL service
        run: sudo systemctl start mysql
        
      - name: Check MySQL service status
        run: systemctl status mysql

      - name: Build
        run: dotnet build --configuration Release

      - name: Test
        run: dotnet test --no-restore --verbosity normal
